import time
from fastapi import FastAPI, Request


# Middleware
# A "middleware" is a function that works with every 
# request before it is processed by any specific path operation. 
# And also with every response before returning it.

# Middleware Features
    # It takes each request that comes to your application.
    # It can then do something to that request or run any needed code.
    # Then it passes the request to be processed by the rest of the application (by some path operation).
    # It then takes the response generated by the application (by some path operation).
    # It can do something to that response or run any needed code.
    # Then it returns the response.

app = FastAPI()

# Create a Middleware
# To create a middleware you use the decorator @app.middleware("http") on top of a function.

@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    response.headers["X-Process-Time"] = str(process_time)
    return response
